services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/src/frontend
      - /usr/src/frontend/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
