services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2    # caches Maven dependencies
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    command: mvn spring-boot:run